[project]
name = "edges-bowman2018-pipeline"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "edges-analysis==8.0.0",
    "edges-pipeline-utils",
    "toml>=0.10.2",
]

[tool.uv.sources]
edges-pipeline-utils = { git = "https://github.com/edges-collab/edges-pipeline-utils" }
edges-analysis = { git = "https://github.com/edges-collab/edges-analysis" }
